# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tangle.adapter.v1alpha1 import adapter_pb2 as tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tangle/adapter/v1alpha1/adapter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdapterServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTargets = channel.unary_unary(
                '/tangle.adapter.v1alpha1.AdapterService/ListTargets',
                request_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.ListTargetsRequest.SerializeToString,
                response_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.ListTargetsResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/tangle.adapter.v1alpha1.AdapterService/GetCapabilities',
                request_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TargetRef.SerializeToString,
                response_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.Capabilities.FromString,
                _registered_method=True)
        self.GetDeviceState = channel.unary_unary(
                '/tangle.adapter.v1alpha1.AdapterService/GetDeviceState',
                request_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TargetRef.SerializeToString,
                response_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.DeviceState.FromString,
                _registered_method=True)
        self.WatchDeviceState = channel.unary_stream(
                '/tangle.adapter.v1alpha1.AdapterService/WatchDeviceState',
                request_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TargetRef.SerializeToString,
                response_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.DeviceState.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/tangle.adapter.v1alpha1.AdapterService/SubmitTask',
                request_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskHandle.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/tangle.adapter.v1alpha1.AdapterService/GetTask',
                request_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskRef.SerializeToString,
                response_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskStatus.FromString,
                _registered_method=True)
        self.WatchTask = channel.unary_stream(
                '/tangle.adapter.v1alpha1.AdapterService/WatchTask',
                request_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskRef.SerializeToString,
                response_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskStatus.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/tangle.adapter.v1alpha1.AdapterService/CancelTask',
                request_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskRef.SerializeToString,
                response_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.OpenSession = channel.unary_unary(
                '/tangle.adapter.v1alpha1.AdapterService/OpenSession',
                request_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.SessionHandle.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/tangle.adapter.v1alpha1.AdapterService/CloseSession',
                request_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.SessionHandle.SerializeToString,
                response_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.CloseSessionResponse.FromString,
                _registered_method=True)


class AdapterServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListTargets(self, request, context):
        """Discovery ---------------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceState(self, request, context):
        """Dynamic state: status, queue, calibration snapshot. Cheap; polled or streamed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchDeviceState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """Execution ---------------------------------------------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenSession(self, request, context):
        """Sessions (only if Capabilities.sessions = true) ---------------------------
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdapterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTargets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTargets,
                    request_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.ListTargetsRequest.FromString,
                    response_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.ListTargetsResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TargetRef.FromString,
                    response_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.Capabilities.SerializeToString,
            ),
            'GetDeviceState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceState,
                    request_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TargetRef.FromString,
                    response_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.DeviceState.SerializeToString,
            ),
            'WatchDeviceState': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchDeviceState,
                    request_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TargetRef.FromString,
                    response_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.DeviceState.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.SubmitTaskRequest.FromString,
                    response_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskHandle.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskRef.FromString,
                    response_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskStatus.SerializeToString,
            ),
            'WatchTask': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchTask,
                    request_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskRef.FromString,
                    response_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskStatus.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskRef.FromString,
                    response_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.CancelTaskResponse.SerializeToString,
            ),
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.OpenSessionRequest.FromString,
                    response_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.SessionHandle.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.SessionHandle.FromString,
                    response_serializer=tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.CloseSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tangle.adapter.v1alpha1.AdapterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tangle.adapter.v1alpha1.AdapterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdapterService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTargets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangle.adapter.v1alpha1.AdapterService/ListTargets',
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.ListTargetsRequest.SerializeToString,
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.ListTargetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangle.adapter.v1alpha1.AdapterService/GetCapabilities',
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TargetRef.SerializeToString,
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.Capabilities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangle.adapter.v1alpha1.AdapterService/GetDeviceState',
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TargetRef.SerializeToString,
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.DeviceState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchDeviceState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tangle.adapter.v1alpha1.AdapterService/WatchDeviceState',
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TargetRef.SerializeToString,
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.DeviceState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangle.adapter.v1alpha1.AdapterService/SubmitTask',
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.SubmitTaskRequest.SerializeToString,
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangle.adapter.v1alpha1.AdapterService/GetTask',
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskRef.SerializeToString,
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tangle.adapter.v1alpha1.AdapterService/WatchTask',
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskRef.SerializeToString,
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangle.adapter.v1alpha1.AdapterService/CancelTask',
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.TaskRef.SerializeToString,
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangle.adapter.v1alpha1.AdapterService/OpenSession',
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.OpenSessionRequest.SerializeToString,
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.SessionHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tangle.adapter.v1alpha1.AdapterService/CloseSession',
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.SessionHandle.SerializeToString,
            tangle_dot_adapter_dot_v1alpha1_dot_adapter__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
